os:
  - linux
  - osx

language: c

env:
  # test against both stable & devel
  - BRANCH=stable
  - BRANCH=devel

cache:
  directories:
    - "$HOME/.nimble"
    - "$HOME/.choosenim"

matrix:
  allow_failures:
    - env: BRANCH=devel
  fast_finish: true

install:
  - export CHOOSENIM_CHOOSE_VERSION=$BRANCH
  - |
      curl https://nim-lang.org/choosenim/init.sh -sSf > init.sh
      sh init.sh -y
  - export PATH=$HOME/.nimble/bin:$PATH
  - nimble refresh -y

script:
  - nimble installWithDeps
  - nimble test
